# Arguments
prompt: zero_v1
train_seed: 2024

# SFTScriptArguments
dataset_name: arranonymsub/HiCUPID
dataset_train_split: train
dataset_test_split: test

# SFTConfig
dataset_text_field: null
packing: false
max_seq_length: 18432
dataset_num_proc: 16
dataset_batch_size: 1000
model_init_kwargs: null
dataset_kwargs:
  skip_prepare_dataset: true
use_liger: true

# TrainingArguments
output_dir: output/peft/sft/lora/Qwen2.5-7B-Instruct  # TODO
eval_strategy: "no"
per_device_train_batch_size: 4
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
torch_empty_cache_steps: 1
learning_rate: 2e-4  # TODO
max_grad_norm: 0.3
num_train_epochs: 3  # TODO
lr_scheduler_type: cosine
warmup_ratio: 0.03
logging_steps: 1
save_strategy: epoch
# save_steps: 0.1
bf16: true
tf32: true
# eval_steps: 0.1
dataloader_num_workers: 16
remove_unused_columns: false
optim: adamw_torch_fused
# group_by_length: true
report_to: tensorboard
push_to_hub: false
resume_from_checkpoint: null
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# ModelConfig
model_name_or_path: Qwen/Qwen2.5-7B-Instruct  # TODO
torch_dtype: bfloat16
trust_remote_code: false
attn_implementation: flash_attention_2
use_peft: true
lora_r: 256  # TODO
lora_alpha: 512  # TODO
lora_dropout: 0.05
lora_target_modules: all-linear
lora_modules_to_save: null
lora_task_type: CAUSAL_LM
use_rslora: false
load_in_8bit: false
load_in_4bit: false
bnb_4bit_quant_type: nf4
use_bnb_nested_quant: false
